### ISSUE TITLE
Add a feature flag for reverse proxy metrics collection

### ISSUE THREAD

**Issue by viveksyngh** [projectcapsule/capsule-proxy#227]
We should add a feature flag in capsule proxy to enable/disable the collection for metrics using the metrics middleware

**Comment by oliverbaehler** [comment]
Hi @viveksyngh, do you still intend to implement this feature? Do you need any assistance? :)

**Comment by prometherion** [comment]
I remember we had some issues while implementing the metrics middleware, that led us to evaluate a toggle for the metrics.

Not sure if it's still needed, tho.

**Comment by oliverbaehler** [comment]
Stale
