### ISSUE TITLE
Question: Any plan to replace gorilla/mux with any other framework?

### ISSUE THREAD

**Issue by sagar-jadhav** [projectcapsule/capsule-proxy#284]
[gorilla/mux](https://github.com/gorilla/mux) project is achieved and no longer under active maintenance and in capsule-proxy `gorilla/mux` is used in [webserver.go](https://github.com/clastix/capsule-proxy/blob/master/internal/webserver/webserver.go) So are there any plans to replace mux with any other framework?

**Comment by prometherion** [comment]
I'm open for discussion about it, sure!

Let's start the discussion about which other framework could be used.

**Comment by sagar-jadhav** [comment]
Sure @prometherion I'll search other frameworks and get back to you.

**Comment by sagar-jadhav** [comment]
@prometherion I found https://github.com/go-chi/chi interesting. 

- Has a regex support
- Fast as per https://github.com/go-chi/chi#benchmarks 
- after looking at issues and PR's looks like it is under active development/maintenance

Above are few points which favours `chi`. I also find this nice blog on https://mariocarrion.com/2022/12/19/gorilla-mux-archived-migration-path.html alternatives.

let's get feedback from others as well :)

**Comment by prometherion** [comment]
Chi's DSL looks like the gorilla/mux one, I like it.

Any remark on this @MaxFedotov @oliverbaehler?

**Comment by MaxFedotov** [comment]
Nope, I've also looked on it a few days ago as a replacement for our services using gorilla-mux

**Comment by prometherion** [comment]
@sagar-jadhav unless @oliverbaehler has something against Chi, and I don't think so, it would be great if we could start this refactoring.

Would you like to take care of it, or anything I can help you with?

**Comment by sagar-jadhav** [comment]
@prometherion I and @rakshpatel had a discussion about this issue and he shares his interest in working on this task. So could you please assign this task to him. Thanks

**Comment by prometherion** [comment]
I would love Sagar, but @rakshpatel has to comment the issue to assign him, first!

**Comment by prometherion** [comment]
Removing @rakshpatel due to inactivity, still open as a good first issue.

**Comment by luisdavim** [comment]
Gorilla mux is active again.

**Comment by prometherion** [comment]
Closing since not required anymore.
