### ISSUE TITLE
can list all pod in all namespace under a tenant?

### ISSUE THREAD

**Issue by zhoushuke** [projectcapsule/capsule-proxy#303]
# Describe the feature
capsule-proxy can support list cluster-scope resource like ns,node in a tenant.
but if I'm a tenant owner,I want to list namespaced-scope resource(pods for example)with all ns under tenant, there is a way? 

for example
kubctl get pod -A
even I'm tenant owner,this command output no permission since -A stands for all namespace, if capsule-proxy can transfer -A to only all namespaces owned tenant owner,that's very helpful

# What would the new user story look like?

How would the new interaction with Capsule-Proxy look like?
Feel free to add a diagram if that helps explain things.

# Expected behavior
A clear and concise description of what you expect to happen.

**Comment by prometherion** [comment]
The assign command here doesn't work, besides the fact that are maintainers picking up the decision about features prioritization, and assignment.

**Comment by prometherion** [comment]
This would be possible once we address clastix/capsule#756: the basic concept is to label all pods in the Tenant namespaces as `capsule.clastix.io/tenant=$TNT_NAME` in order to proxy to the API server with the required selector.

**Comment by zhoushuke** [comment]
clearly, issue closed.

**Comment by prometherion** [comment]
There's no need to close this issue
It's something that we can work on.

**Comment by oliverbaehler** [comment]
I am happy to spin up a draft. The only tricky part is with existing resources (eg. we would have to restart all pods with this change to add the labels).

**Comment by ppeereb1** [comment]
Also interested in this feature! Would be nice if other namespaced resources are supported as well: services, networkpolicies, pvc etc.

**Comment by oliverbaehler** [comment]
Hi @ppeereb1, our current implementation indexes all namespaced resources (even crds!). You can expect this feature to be published in Q1

**Comment by prometherion** [comment]
Just for the sake of clarity, we're going to support custom resource instances listing, not supporting that installation of Cards at the Tenant level.

**Comment by ppeereb1** [comment]
Awesome thanks! Would be nice if you could install crd's on a tenant level as well but can imagine this is hard to implement

**Comment by prometherion** [comment]
It's outside of project's scope which is providing governance to an existing Kubernetes cluster, rather than doing virtual clusters which being [several challenges](https://rafay.co/the-kubernetes-current/key-considerations-when-implementing-virtual-kubernetes-clusters/).

**Comment by oliverbaehler** [comment]
Feature was implemented. Keeping issue to document a guide for usage.

**Comment by anatolychernov** [comment]
> Feature was implemented. Keeping issue to document a guide for usage.

Hello @oliverbaehler,

Could you clarify, as I can see this feature hasn't been released yet?

**Comment by ppeereb1** [comment]
"it’s preview, we are going to release 0.7.0 where a crucial fix is included" From slack

**Comment by anatolychernov** [comment]
Hello,

I upgraded capsule and capsule-proxy to version 0.7.0.

It seems we are still not able to execute the ‘kubectl get pods –all-namespaces’ command because capsule-proxy says:
“Error from server (Forbidden): pods is forbidden: User ‘alice’ cannot list resource ‘pods’ in API group ‘’ at the cluster scope.”

In this example, ‘alice’ has permissions for ‘tenant1’ and ‘tenant2’, which contain namespaces with pods.
Am I correct in expecting that we should have the ability to execute the ‘kubectl get pods –all-namespaces’ command to list all pods under all of the user’s(alice) tenants and their namespaces?

**Comment by prometherion** [comment]
I'm actively using this feature and it's working as expected, of course, the feature flag must be enabled, such as `--feature-gates=ProxyAllNamespaced=true`.

**Comment by prometherion** [comment]
Closing the issue since released with v0.6.0, further bugs can be tracked in different issues.

Questions must be raised in the Discussion section, or in the [Slack channel](https://kubernetes.slack.com/archives/C03GETTJQRL).
