### ISSUE TITLE
Chart update - HPA to autoscaling/v2 as autoscaling/v2beta1 is deprecated

### ISSUE THREAD

**Issue by akhilkrishnakumar-tomtom** [projectcapsule/capsule-proxy#312]
# Describe the feature

Chart update - HPA to autoscaling/v2 as autoscaling/v2beta1 is [deprecated](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125) 

# What would the new user story look like?

How would the new interaction with Capsule-Proxy look like?
Feel free to add a diagram if that helps explain things.

# Expected behavior
A clear and concise description of what you expect to happen.

**Comment by prometherion** [comment]
Thanks for the report, @oliverbaehler addressed it with #318.
