### ISSUE TITLE
Kubernetes Dashboard crashing on startup with capsule-proxy

### ISSUE THREAD

**Issue by sybnex** [projectcapsule/capsule-proxy#315]
We have a runing setup of Kubernetes with Guard (AAD integration) and the official Kubernetes Dashboard. After login over hte oauth2-proxy we having a jwt token which will be used automatically in the dashboard.

As I'm triyng to implementd capsule in our setup I tried to use the capsule-proxy for the users to see their workload over the dashboard. So I've deployed the capsule-proxy with helm on a seprated ingress url. 

For the kubectl setup this is working fine and the users can only see their workload.
Starting to implement the capsule-proxy in the dashboard setup, I got some issues. 

I added the param `--apiserver-host=http://capsule-proxy.capsule-system:9001` into the dashboard args section but the dashboard cannot startup with the following erros: 

```2023/10/19 07:00:00 Using apiserver-host location: http://capsule-proxy.capsule-system:9001
2023/10/19 07:00:00 Using namespace: kubernetes-dashboard
2023/10/19 07:00:00 Skipping in-cluster config
2023/10/19 07:00:00 Using random key for csrf signing
2023/10/19 07:00:00 Successful initial request to the apiserver, version:
2023/10/19 07:00:00 Generating JWE encryption key
2023/10/19 07:00:00 New synchronizer has been registered: kubernetes-dashboard-key-holder-kubernetes-dashboard. Starting
2023/10/19 07:00:00 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kubernetes-dashboard
2023/10/19 07:00:00 Synchronizer kubernetes-dashboard-key-holder-kubernetes-dashboard exited with error: unexpected object: &Secret{ObjectMeta:{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []},Data:map[string][]byte{},Type:,StringData:map[string]string{},Immutable:nil,}
2023/10/19 07:00:00 Storing encryption key in a secret
panic: cannot retrieve user and group: unauthenticated users not supported
```
In the capsule-proxy log I can see the following:

```{"level":"Level(-4)","ts":"2023-10-19T07:00:00.075Z","logger":"proxy","msg":"allowed url path.","url path":"/version"}
2023/10/19 07:00:00 http: superfluous response.WriteHeader call from github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1 (recovery.go:73)
2023/10/19 07:00:00 cannot retrieve user and group: unauthenticated users not supported
2023/10/19 07:00:00 http: superfluous response.WriteHeader call from github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1 (recovery.go:73)
2023/10/19 07:00:00 cannot retrieve user and group: unauthenticated users not supported
2023/10/19 07:00:00 http: superfluous response.WriteHeader call from github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1 (recovery.go:73)
2023/10/19 07:00:00 cannot retrieve user and group: unauthenticated users not supported
2023/10/19 07:00:00 http: superfluous response.WriteHeader call from github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1 (recovery.go:73)
2023/10/19 07:00:00 cannot retrieve user and group: unauthenticated users not supported
```

So the dashboard tries to get `/version` from the API but is not allowed and crashed. Did I missed something in the setup? Because I don't understand why the dashboard does a query without any auth to the api and I can find any hints in your docu about that.

- Kubernetes Dashboard: 2.7.0 and 3.0.0-alpha
- Capsule version: 0.3.3
- Capsule-Proxy version: 0.4.4
- Kubernetes version: 1.26.6

**Comment by prometherion** [comment]
Thanks for opening this, @sybnex!

Did you take a look at this [guide](https://github.com/clastix/coaks-baseline-architecture/blob/master/guides/05-kubernetes-dashboard.md)? It's related to Azure and AAD, wondering if you're following the same steps and failing nevertheless of it.

**Comment by sybnex** [comment]
Hi, 

thanks for your response. We are not using AKS in this setup. We are having an onPrem Kubernetes setup with kubeadm.
And the main problem is not the OICD interface, because this is working without capsule. Not exaclty with the same setup but similiar (caddy with security plugin).

But the Kubernetes Dashboard is running into a **CrashLoopBackOff** and can't even start if I add the capsule-proxy in front of it. Because it tries to get `/version` path from the API over the capsule-proxy on the startup phase. And that's what I'm not understanding. 

That's why I was wondering how can this be working in your setup, do you see the `/version` request as well during the startup of the dashboard? If yes, how it is authorised? 

This `/version` path is on the same level as the `/api` path. I'm really confused about this ...

**Comment by prometherion** [comment]
> We are not using AKS in this setup

My bad, I blindly read AAD and thought about AKS.

> But the Kubernetes Dashboard is running into a **CrashLoopBackOff** and can't even start if I add the capsule-proxy in front of it. Because it tries to get `/version` path from the API over the capsule-proxy on the startup phase. And that's what I'm not understanding.

I linked you the Capsule over AKS link since I worked on how to integrate Capsule with the default Kubernetes dashboard, and I didn't encounter such a problem. Shame on me I didn't check the version I tested with. 🫠

I just tested the `/version` endpoint, and on a freshly installed Kubernetes cluster its endpoint is publicly reachable, thus I think we could avoid the auth middleware for that endpoint.

https://github.com/clastix/capsule-proxy/blob/ab4e7e72220ebaec75793e4c0f02a01a3c47e886/internal/webserver/webserver.go#L65

@MaxFedotov @oliverbaehler any remark on removing the `/version` endpoint from the authentication middleware?

**Comment by sybnex** [comment]
btw. I just saw that I missed to post the log line for the /version part:

```
{"level":"Level(-4)","ts":"2023-10-19T09:17:55.312Z","logger":"proxy","msg":"allowed url path.","url path":"/version"}
2023/10/19 09:17:55 http: superfluous response.WriteHeader call from github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1 (recovery.go:73)
2023/10/19 09:17:55 cannot retrieve user and group: unauthenticated users not supported
```

**Comment by prometherion** [comment]
Not a big problem, @sybnex.

I think we took for granted the `version` endpoint was under RBAC, and I think it's safe from the security standpoint, but not for all the Kubernetes distributions and the hardened one.

What we need to do, there, is to remove the `/version` from the intercepted routes, and allow the proxy-pass to the upstream server (aka the Kubernetes API Server).

I can open a PR, it would be great if you could build the image on your own and test it on your environment.

**Comment by prometherion** [comment]
You're right, I'm working on a PR to address this, and I'll be back to it ASAP

**Comment by sybnex** [comment]
Hi @prometherion ... any news on that?

**Comment by prometherion** [comment]
There's nothing worse in the Open Source world than asking: _any (update/news) on (this/that)?_

The Capsule project is in the middle of a reorganization due to the CNCF Sandbox process, furthermore, it's addressing several security assessments requested by the Cloud Native Security Slam 2023 edition.

There are several other ways to speed up the features development, or the bug-fixing, also considering that CLASTIX is the commercial company founding the project by paying up engineers who have limited time, but definitely, it's not by commenting on the issue.

**Comment by sybnex** [comment]
Today I have created a complete new VM with a k3s instance and deployed the whole chain in a very simple manner.
- kubernetes dashboard v3
- capsule
- capsule-proxy
- cert-manager
- ingress-nginx

Everything with a plain SA-Token works perfectly over the capsule-proxy as excpected. But again the kubernetes dashbard is not able to startup with the given logs above. I found a similar open issue on the github dashboard => https://github.com/kubernetes/dashboard/issues/7904

I think we could get more infos about the source problem, if the capsule-proxy would have more verbose logging. I will try to sniff the network traffic to get an idea. 

Do u think u can add more logging?

**Comment by sybnex** [comment]
ok, on the single node cluster is was easy to get the network sniffing running. Here are the result from one startup:

dashboard:

```
GET /version HTTP/1.1
Host: capsule-proxy.capsule-system:9001
User-Agent: dashboard/UNKNOWN
Accept: application/vnd.kubernetes.protobuf, */*
Accept-Encoding: gzip
```

proxy answer:
```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"cannot retrieve user and group: unauthenticated users not supported","reason":"Forbidden","code":403}
```


dashboard:
```
GET /api/v1/namespaces/kubernetes-dashboard/secrets/kubernetes-dashboard-key-holder HTTP/1.1
Host: capsule-proxy.capsule-system:9001
User-Agent: dashboard/UNKNOWN
Accept: application/vnd.kubernetes.protobuf, */*
Accept-Encoding: gzip
```

proxy answer:
```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"cannot retrieve user and group: unauthenticated users not supported","reason":"Forbidden","code":403}
```


dashboard:
```
POST /api/v1/namespaces/kubernetes-dashboard/secrets HTTP/1.1
Host: capsule-proxy.capsule-system:9001
User-Agent: dashboard/UNKNOWN
Content-Length: 2257
Accept: application/vnd.kubernetes.protobuf, */*
Content-Type: application/vnd.kubernetes.protobuf
Accept-Encoding: gzip
```

proxy-answer:
```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"cannot retrieve user and group: unauthenticated users not supported","reason":"Forbidden","code":403}
```

So I tried to add the dashboard namespace to a freshly created tenant with the dashboard service account as owner like:

```
---
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: sys
spec:
  owners:
  - name: system:serviceaccount:kubernetes-dashboard:kubernetes-dashboard
    kind: ServiceAccount
---
apiVersion: capsule.clastix.io/v1beta2
kind: CapsuleConfiguration
...
  userGroups:
  - capsule.clastix.io
  - system:serviceaccounts:kubernetes-dashboard
```

But after restarting of the dashboard, the result stays the same and the proxy doesn't auth the request as before.

I guess here comes the serviceaccount issue from above again into the game.

Not sure how to go on

**Comment by prometherion** [comment]
The Dashboard mustn't be part of a Tenant, otherwise, it will have a sort of egg-chicken problem.

The ideal plan would be something like this:
- the Dashboard starts with a ServiceAccount, with the required RBAC
- the Dashboard requests should be sent to the Capsule Proxy
- the Capsule Proxy should ignore those requests, since not part of a Tenant, by extracting user and groups from the Bearer token
- when users log into the Dashboard, their tokens must be used to perform the OAuth2 flow

**Comment by sybnex** [comment]
Hi, actual status of our setup right now:

- The Dashboard uses its own serviceaccount ✅
- The Dashboard is configured to the capsule proxy ✅
- Capsule Proxy ignores the requests ❌ (capsule proxy deny the request qith "unauthorized")
- User coming from our OAuth portal using their tokens for the Dashboard and it works with Capsule ✅

**Comment by sybnex** [comment]
If somebody find this, I got the solution with the descibred combination.

You have to add those 2 args in the latest Kubernetes dashboard version to the api deployment to make things happend:

- \- --apiserver-host=https://capsule.[your-ingress-domain]
- \- --act-as-proxy=true

**Comment by prometherion** [comment]
Lovely @sybnex and thanks for reporting this back, is definitely gold! 🤩 

I'll try to give this a try with a customer of CLASTIX to ensure it fixes the issue!
