### ISSUE TITLE
Capsule proxy not validating the user requests after certain time after the Kubernetes upgrade to 1.30.1

### ISSUE THREAD

**Issue by gowthamvasan** [projectcapsule/capsule-proxy#587]
# Bug description

Capsule proxy requests are rejected with 401 unauthorized error . The user get this following error

Error: error validating "STDIN": error validating data: failed to download openapi: the server has asked for the client to provide credentials; if you choose to ignore these errors, turn validation off with --validate=false

To fix temporarily , we have to restart the capsule proxy pod every one hour. So whenever the pod get restarted , the users not facing any issue for about 40 to 50 mins. 

# How to reproduce

# Expected behavior

The user requests are validated and authorized without any error

# Logs

No logs apart from this , we have enabled log level 10 

{"level":"Level(-4)","ts":"2024-11-28T13:15:44.994Z","logger":"proxy","msg":"impersonating for the current request","username":"1e3b32dc-7117-47eb-8efc-488dd0ea7d12","groups":["7cadb0b3-8d95-4a7b-a2c3-1883a7387756","0ac5bef3-d2f4-4139-a7b8-8ec12b7ff0a8","system:authenticated"],"uri":"/openapi/v2"}
{"level":"Level(-5)","ts":"2024-11-28T13:15:44.994Z","logger":"proxy","msg":"debugging request","uri":"/openapi/v2?timeout=32s","method":"GET"}

# Additional context

- Capsule-Proxy version: 0.7.0
- Helm Chart version: capsule-proxy-0.7.0
- Kubernetes version: 1.30.1

**Comment by prometherion** [comment]
I'd say this is a duplicate if #565, may I ask you to give a try with the v0.8.0 release, please?

**Comment by gowthamvasan** [comment]
> #565

@prometherion  Thanks for sharing the other related bugs. But I dont see version 0.8.0 released .

**Comment by prometherion** [comment]
Sorry but I'm not getting your point: v0.8.0 has been released using [GitHub releases](https://github.com/projectcapsule/capsule-proxy/releases/tag/v0.8.0), as well as [OCI image](https://github.com/projectcapsule/capsule-proxy/pkgs/container/capsule-proxy/306535839?tag=v0.8.0) hosted on GHCR and related [Helm Chart](https://github.com/projectcapsule/capsule-proxy/pkgs/container/charts%2Fcapsule-proxy/306533803?tag=0.8.0).

**Comment by gowthamvasan** [comment]
Thanks @prometherion , I found the latest version and deployed as a fix in our environments. We will monitor for few days

**Comment by prometherion** [comment]
Thanks, feel free to open this in case the issue persists!
